#check package-lock file version

name: lockfileVersion check

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  version-check:
    uses: Jawayria/.github/.github/workflows/lockfileversion-check.yml@jawayria/pkg-lock-check
    
